jwt:
  secret: YWFzbGtqZGx6a3huY21haHJvd3VlaHJzbWRueGtqZGhmbGtzZGhmd2VsdXJoc2tmbnNk

server:
  port: 8080

client:
  host:
    url: http://localhost:3000

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/mybob
    username: root
    password: selvas1122!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 100